Year: {movie.Year + '\n'}
Released: {movie.Released + '\n'}
Runtime: {movie.Runtime + '\n'}
Genre: {movie.Genre + '\n'}
Director: {movie.Director + '\n'}
Writer: {movie.Writer + '\n'}
Actors: {movie.Actors + '\n'}
Language: {movie.Language + '\n'}
Awards: {movie.Awards + '\n'}
Production: {movie.Production + '\n'}
